import { NextResponse } from "next/server";
import { renderToStream } from "@react-pdf/renderer";
import { createClient } from "@/lib/supabase/server";
import { NoticePdf } from "@/lib/pdf/notice-document";
import { renderTemplate } from "@/lib/pdf/render-template";

export const runtime = "nodejs";

export async function GET(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const supabase = await createClient();

  const { data: caseRow, error } = await supabase
    .from("cases")
    .select(`
      id, jurisdiction_code,
      org:organizations ( name ),
      engagement:engagements (
        scope, fee_arrangement, status,
        attorney:attorneys ( full_name, bar_id, email )
      )
    `)
    .eq("id", id)
    .order("created_at", { ascending: false, foreignTable: "engagements" })
    .limit(1, { foreignTable: "engagements" })
    .single();
  if (error || !caseRow) return NextResponse.json({ error: error?.message ?? "Not found" }, { status: 404 });

  const engagements = (caseRow.engagement ?? []) as { scope: string; fee_arrangement: { label?: string; amount_dollars?: number }; attorney: { full_name: string; bar_id: string }[] | { full_name: string; bar_id: string } | null }[];
  const eng = engagements[0];
  if (!eng) return NextResponse.json({ error: "No engagement on this case" }, { status: 404 });
  const attorney = Array.isArray(eng.attorney) ? eng.attorney[0] : eng.attorney;
  const org = Array.isArray(caseRow.org) ? caseRow.org[0] : caseRow.org;

  const { data: tpl } = await supabase
    .from("form_templates")
    .select("body")
    .eq("jurisdiction_code", "US")
    .eq("type", "ENGAGEMENT_LETTER")
    .order("effective_from", { ascending: false })
    .limit(1)
    .maybeSingle();
  if (!tpl) return NextResponse.json({ error: "Engagement letter template not found" }, { status: 500 });

  const today = new Date().toISOString().slice(0, 10);
  const fee = eng.fee_arrangement;
  const fee_summary = fee?.amount_dollars
    ? `${(fee.label ?? "fee").replace(/_/g, " ")} — $${fee.amount_dollars}`
    : (fee?.label ?? "Fee terms to be determined");

  const body = renderTemplate(tpl.body, {
    landlord_name: org?.name ?? "Client",
    attorney_name: attorney?.full_name ?? "Counsel",
    attorney_bar:  attorney?.bar_id ?? "—",
    scope:         eng.scope,
    fee_summary,
    jurisdiction_code: caseRow.jurisdiction_code,
    today,
  });

  const stream = await renderToStream(
    NoticePdf({
      title: "ENGAGEMENT LETTER",
      body,
      citation: null,
      landlordName: org?.name ?? "Client",
      todayLabel: today,
      identityFooter: "Generated by Eviction Management — case " + id,
    }),
  );

  return new NextResponse(stream as unknown as ReadableStream, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="engagement-${id}.pdf"`,
    },
  });
}
