import { NextResponse } from "next/server";
import { renderToStream } from "@react-pdf/renderer";
import { createClient } from "@/lib/supabase/server";
import { getNoticeTemplate } from "@/lib/rules/db";
import { NoticePdf } from "@/lib/pdf/notice-document";
import { dollars, renderTemplate } from "@/lib/pdf/render-template";

export const runtime = "nodejs";

interface CaseRow {
  id: string;
  computed: { amount_owed_cents?: number | null; as_of_date?: string | null;
    rules?: { courtVenue?: { court_name: string } } } | null;
  jurisdiction_code: string;
  lease: {
    property: { address_line1: string; address_line2: string | null; city: string; state: string; postal_code: string };
    lease_renters: { renter: { full_name: string } }[];
  };
  org: { name: string };
}

export async function GET(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const supabase = await createClient();

  const { data, error } = await supabase
    .from("cases")
    .select(`
      id, computed, jurisdiction_code,
      lease:leases (
        property:properties ( address_line1, address_line2, city, state, postal_code ),
        lease_renters ( renter:renters ( full_name ) )
      ),
      org:organizations ( name )
    `)
    .eq("id", id)
    .single();
  if (error || !data) return NextResponse.json({ error: error?.message ?? "Not found" }, { status: 404 });

  const c = data as unknown as CaseRow;
  const property = c.lease.property;
  const renterNames = (c.lease.lease_renters ?? []).map((lr) => lr.renter?.full_name).filter(Boolean).join(" and ");
  const propertyAddress = [
    property.address_line1, property.address_line2,
    `${property.city}, ${property.state} ${property.postal_code}`,
  ].filter(Boolean).join(", ");

  const supabaseSrv = await createClient();
  const { data: tpl } = await supabaseSrv
    .from("form_templates")
    .select("*")
    .eq("jurisdiction_code", `US-${c.jurisdiction_code.split("-")[1] ?? "GA"}`)
    .eq("type", "COMPLAINT")
    .order("effective_from", { ascending: false })
    .limit(1)
    .maybeSingle();

  // Fall back to the per-state notice template if no complaint template seeded.
  const template = tpl ?? (await getNoticeTemplate(c.jurisdiction_code.split("-")[1] ?? "GA"));
  if (!template) return NextResponse.json({ error: "Template not found" }, { status: 500 });

  const today = new Date().toISOString().slice(0, 10);
  const vars = {
    landlord_name: c.org.name,
    tenant_name: renterNames || "Tenant",
    property_address: propertyAddress,
    court_name: c.computed?.rules?.courtVenue?.court_name ?? "the appropriate court",
    amount_owed_cents: c.computed?.amount_owed_cents ?? 0,
    amount_owed_dollars: dollars(c.computed?.amount_owed_cents),
    as_of_date: c.computed?.as_of_date ?? today,
    today,
  };

  const body = renderTemplate(template.body, vars);
  const stream = await renderToStream(
    NoticePdf({
      title: "DISPOSSESSORY AFFIDAVIT",
      body,
      citation: "OCGA § 44-7-50 et seq.",
      landlordName: c.org.name,
      todayLabel: today,
      identityFooter: "Generated by Eviction Management — case " + id,
    }),
  );

  return new NextResponse(stream as unknown as ReadableStream, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="complaint-${id}.pdf"`,
    },
  });
}
